name: LightningJoin
version: 0.4
api: 1.13.0
main: Light\Main
author: Jelly9912
description: Lightning on player join and command
commands:
  strike:
    default: OP
    description: Make a lightning over player
permissions:
  strike.command:
    default: OP
