name: LightningJoin
version: 0.2
api: 1.13.0
main: Light\Main
author: Jelly9912
description: Lightning on player join and respawn
commands:
  strike:
    usage: /strike <player>
    default: op
    description: Make a lightning over player
